Feature: Add Speaker Notes for Testing Slides
dbt-labs/learn.getdbt.com pull request #200
Opened 2022-01-18 16:28 UTC by christineberger

These changes add speaker notes for the testing slides.

2022-02-03 14:56 UTC, coapacetic approved these changes
One very quick fix to implement - otherwise LGTM 🚀 

I'll yield to @alexiswo for another instructional review before merging.

2022-02-03 14:56 UTC, coapacetic commented on _lessons/sources.html
> +Teaching Note: Think of a good story to share about a specific situation when dbt source functionality would have really helped avoid a painful mistake or burdensome work.
praise: ohhh I like this note to share a real data story here.

2022-02-03 14:56 UTC, coapacetic commented on _lessons/sources.html
> +Teaching Note: In case anyone asks 'What does the 'version: 2' in all the yml file code snippets do? Can/should I update yml code versions?'. Answer: "Once upon a time, the structure of these .yml fi
appreciation: definitely helpful for newer instructors - we almost always get asked this.

2022-02-03 14:56 UTC, coapacetic commented on _lessons/who-is-analytics-engineer.html
> +Slide setup: When did people first start hearing the term 'analytics engineering'? Analytics Engineering is relatively new. The role of Analytics Engineer is relatively new. To understand it, we need
praise: Nice teacher moves here! you are giving excellent context for why we are talking about traditional data teams

2022-02-03 14:56 UTC, coapacetic commented on _lessons/who-is-analytics-engineer.html
> +- MPP (massively parallel processing) warehouses such as Snowlfake, Redshift, and BigQuery replaced the need for engineers to maintain warehouse infrastructures.
```suggestion
- MPP (massively parallel processing) warehouses such as Snowflake, Redshift, and BigQuery replaced the need for engineers to maintain warehouse infrastructures.
```
quick-fix: small typo

2022-02-09 16:41 UTC, alexiswo requested changes
Requested a couple of tweaks. Thanks Christine!

2022-02-09 16:41 UTC, alexiswo commented on _lessons/testing.html
> +- and then it executs the sql for each test using what's built in our warehouse.
typo: "executs" should be "executes"

2022-02-09 16:41 UTC, alexiswo commented on _lessons/testing.html
> +number - count of 0 is a pass and anything more than 0 is a failure.
Same comment here as above

2022-02-09 16:41 UTC, alexiswo commented on _lessons/testing.html
> +- It's testing he payment_method column.
"he" --> "the"

2022-02-10 20:20 UTC, christineberger commented
Thanks for all the feedback @alexiswo! I applied the changes - can you re-review? =)

2022-02-16 03:35 UTC, alexiswo requested changes
One small typo and we're good to go!

2022-02-16 03:35 UTC, alexiswo commented on _lessons/testing.html
> +The other important piece here is that dbt testa operate on the return of
"testa" --> "tests"

2022-02-16 21:35 UTC, merged